-- ── APK chat history (Supabase-persisted, auto-wipes after the TTL window) ──
-- Stores both AI Chat (chat_screen) and Agent (agent_screen) conversations so
-- they survive the app being closed/reopened. A pg_cron job + opportunistic
-- prune deletes anything past its expires_at.
--
-- ⏳ ADMIN-CONFIGURABLE TTL: the retention window is set from the admin panel
-- (range: 2 days → 2 months) and stored in app_settings (key
-- 'apk_chat_ttl_days'). The app computes each new row's expires_at using that
-- value; this cron simply deletes rows whose expires_at has already passed, so
-- it automatically honours whatever TTL was in effect when each row was created
-- — NO cron change is needed when the admin changes the window.
create table if not exists public.apk_chat_history (
  id           bigint generated by default as identity primary key,
  user_id      text not null,
  scope        text not null,            -- 'chat' | 'wormgpt' | 'agent' | 'lemon'
  role         text not null,            -- 'user' | 'assistant'
  content      text,
  steps        jsonb,                    -- agent live-step notes (optional)
  files        jsonb,                    -- agent output file metadata (optional)
  attachments  jsonb,                    -- user attachment names (optional)
  is_error     boolean default false,
  running      boolean default false,    -- true while an agent task is still in-flight
  client_msg_id text,                     -- client-generated id for de-dup / update
  created_at   timestamptz not null default now(),
  expires_at   timestamptz not null default (now() + interval '2 days')
);

create index if not exists idx_apk_chat_user_scope on public.apk_chat_history (user_id, scope, id);
create index if not exists idx_apk_chat_expires on public.apk_chat_history (expires_at);

-- Service role bypasses RLS; keep RLS disabled to match the rest of this project.
alter table public.apk_chat_history disable row level security;

-- Prune helper (also called opportunistically from the app on read).
create or replace function public.prune_apk_chat_history()
returns void language sql as $$
  delete from public.apk_chat_history where expires_at <= now();
$$;

-- Schedule the prune every 10 minutes via pg_cron (extension already used by
-- this project for wormgpt_memory). Safe if it already exists.
do $$
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    perform cron.unschedule('prune_apk_chat_history')
      where exists (select 1 from cron.job where jobname = 'prune_apk_chat_history');
    perform cron.schedule('prune_apk_chat_history', '*/10 * * * *',
      $cron$ select public.prune_apk_chat_history(); $cron$);
  end if;
end $$;
