'use strict';
// Deterministic presentation engine: varied visual layouts, custom palettes,
// images, speaker notes, native PowerPoint transitions, animated HTML and OOXML QA.
const PptxGenJS = require('pptxgenjs');
const AdmZip = require('adm-zip');

const THEMES = {
  midnight:{bg:'090B18',surface:'15182B',title:'FFFFFF',body:'D8DDF0',accent:'8B5CF6',accent2:'22D3EE',sub:'AAB3D1'},
  ocean:{bg:'061B2C',surface:'0D334B',title:'FFFFFF',body:'D9EFF8',accent:'22C7F0',accent2:'2DD4BF',sub:'A5CEE0'},
  forest:{bg:'09251B',surface:'143C2C',title:'FFFFFF',body:'DCF4E8',accent:'34D399',accent2:'FBBF24',sub:'AAD5C0'},
  sunset:{bg:'2A102C',surface:'4A1D48',title:'FFFFFF',body:'FBE5F1',accent:'FB7185',accent2:'FDBA74',sub:'E0B6D0'},
  slate:{bg:'17202B',surface:'273444',title:'FFFFFF',body:'E4EAF2',accent:'F59E0B',accent2:'60A5FA',sub:'B2BFCE'},
  light:{bg:'F7F8FC',surface:'FFFFFF',title:'111827',body:'334155',accent:'635BFF',accent2:'06B6D4',sub:'64748B'},
  corporate:{bg:'F6F9FC',surface:'FFFFFF',title:'0A2540',body:'334155',accent:'0073E6',accent2:'00A88F',sub:'5B7088'},
};
const cleanHex=v=>String(v||'').replace(/^#/,'').toUpperCase();
function pickTheme(name, colors){
  const key=String(name||'ocean').toLowerCase().replace(/[^a-z]/g,'');
  const t={...(THEMES[key]||THEMES.ocean)};
  if(Array.isArray(colors)){ const c=colors.map(cleanHex).filter(x=>/^[0-9A-F]{6}$/.test(x)); if(c.length===1){t.accent=c[0];t.accent2=c[0];}else if(c.length===2){t.bg=c[1];t.surface=c[1];t.accent=c[0];t.accent2=c[0];}else{if(c[0])t.bg=c[0];if(c[1])t.surface=c[1];if(c[2])t.accent=c[2];if(c[3])t.accent2=c[3];} }
  else if(colors&&typeof colors==='object') for(const k of Object.keys(t)){const c=cleanHex(colors[k]);if(/^[0-9A-F]{6}$/.test(c))t[k]=c;}
  return t;
}
const esc=s=>String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const strip=s=>String(s==null?'':s).replace(/\*\*([^*]+)\*\*/g,'$1').replace(/(^|[^*])\*([^*]+)\*/g,'$1$2').replace(/`([^`]+)`/g,'$1');
const inline=s=>esc(s).replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>');
function normalizeSlides(args){
  if(Array.isArray(args.slides)&&args.slides.length)return args.slides.map((s,i)=>({
    title:s.title||'',subtitle:s.subtitle||'',bullets:Array.isArray(s.bullets)?s.bullets.filter(Boolean):[],content:s.content||'',notes:s.notes||'',
    image:s.image||'',layout:s.layout||'',quote:s.quote||'',attribution:s.attribution||'',metrics:Array.isArray(s.metrics)?s.metrics:[],
    cards:Array.isArray(s.cards)?s.cards:[],chart:s.chart||null,section:!!s.section,transition:s.transition||'',index:i,
  }));
  if(args.markdown)return String(args.markdown).split(/^\s*---\s*$/m).map((part,i)=>{let title='',bullets=[],rest=[];for(const raw of part.split('\n')){const x=raw.trim();if(!x)continue;const h=x.match(/^#{1,3}\s+(.*)$/);if(h&&!title)title=h[1];else if(/^[-*+]\s+/.test(x))bullets.push(x.replace(/^[-*+]\s+/,''));else rest.push(x);}return{title,subtitle:'',bullets,content:rest.join('\n'),notes:'',image:'',layout:'',quote:'',attribution:'',metrics:[],cards:[],chart:null,section:false,transition:'',index:i};}).filter(s=>s.title||s.bullets.length||s.content);
  return [];
}
function layoutFor(s,i){
  if(s.section)return'section'; if(s.quote)return'quote'; if(Array.isArray(s.metrics)&&s.metrics.length)return'metrics'; if(Array.isArray(s.cards)&&s.cards.length)return'cards'; if(s.chart)return'chart';
  if(s.image)return s.layout||(['image-right','image-left','image-full'][i%3]); return s.layout||(['editorial','cards-auto','statement'][i%3]);
}
function buildHtmlDeck({title,subtitle,author,slides,theme,colors,animate=true}){
  slides=normalizeSlides({slides});
  const t=pickTheme(theme,colors); const pages=slides.map((s,i)=>{const layout=layoutFor(s,i);let visual='';
    if(s.image)visual=`<figure><img src="${esc(s.image)}" alt="${esc(s.title||'Presentation visual')}"></figure>`;
    if(s.metrics.length)visual=`<div class="metrics">${s.metrics.map(m=>`<article><b>${inline(m.value)}</b><span>${inline(m.label)}</span></article>`).join('')}</div>`;
    if(s.cards.length)visual=`<div class="cards">${s.cards.map(c=>`<article><h3>${inline(c.title)}</h3><p>${inline(c.text||c.content||'')}</p></article>`).join('')}</div>`;
    if(s.quote)visual=`<blockquote>“${inline(s.quote)}”<cite>${inline(s.attribution||'')}</cite></blockquote>`;
    const body=(s.bullets.length?`<ul>${s.bullets.slice(0,6).map(b=>`<li>${inline(b)}</li>`).join('')}</ul>`:'')+(s.content?`<p>${inline(s.content)}</p>`:'');
    return `<section class="slide ${layout}" data-transition="${esc(s.transition||'fade')}"><div class="orb"></div><header><span>${String(i+1).padStart(2,'0')}</span><h2>${inline(s.title)}</h2>${s.subtitle?`<p>${inline(s.subtitle)}</p>`:''}</header><main>${visual}<div class="copy">${body}</div></main><footer>${inline(title)}</footer></section>`;
  }).join('\n');
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${esc(title)}</title><style>
*{box-sizing:border-box}html,body{margin:0;background:#05070d;font-family:Inter,Segoe UI,Arial,sans-serif}.slide{position:relative;width:1280px;height:720px;overflow:hidden;padding:64px 76px;background:#${t.bg};color:#${t.body};page-break-after:always}.orb{position:absolute;width:500px;height:500px;border-radius:50%;right:-220px;top:-220px;background:radial-gradient(circle,#${t.accent}66,transparent 68%)}header{position:relative;z-index:2;max-width:1120px}header span{font-size:15px;font-weight:800;letter-spacing:.2em;color:#${t.accent}}h1,h2,h3,p{margin:0}h2{color:#${t.title};font-size:48px;line-height:1.06;letter-spacing:-.035em;margin-top:10px;max-width:1000px}header p{font-size:20px;color:#${t.sub};margin-top:12px}main{position:relative;z-index:2;display:grid;grid-template-columns:1fr 1fr;gap:48px;align-items:center;height:500px}.copy p,.copy li{font-size:24px;line-height:1.42}.copy ul{padding:0;list-style:none}.copy li{margin:14px 0;padding-left:28px;position:relative}.copy li:before{content:'';position:absolute;left:0;top:.58em;width:11px;height:11px;border-radius:3px;background:#${t.accent}}figure{margin:0;height:365px;border-radius:24px;overflow:hidden;box-shadow:0 30px 70px #0008;border:1px solid #${t.accent}55}figure img{width:100%;height:100%;object-fit:cover}.image-left figure{order:0}.image-left .copy{order:1}.image-right .copy{order:0}.image-right figure{order:1}.image-full main{display:block}.image-full figure{position:absolute;inset:24px 0 0;height:430px;opacity:.62}.image-full .copy{position:absolute;left:40px;bottom:50px;width:65%;padding:24px;background:#${t.bg}dd;border-radius:18px}.metrics,.cards{grid-column:1/-1;display:grid;grid-template-columns:repeat(3,1fr);gap:22px}.metrics article,.cards article{padding:28px;border-radius:22px;background:#${t.surface};border:1px solid #${t.accent}44}.metrics b{display:block;font-size:48px;color:#${t.accent}}.metrics span{font-size:18px;color:#${t.sub}}.cards h3{font-size:24px;color:#${t.title};margin-bottom:10px}.cards p{font-size:17px;line-height:1.45}blockquote{grid-column:1/-1;font-size:46px;line-height:1.22;color:#${t.title};font-weight:700;max-width:1000px}cite{display:block;font-size:18px;color:#${t.accent};margin-top:30px;font-style:normal}.section main,.statement main{display:flex}.section h2,.statement h2{font-size:64px}.section .copy,.statement .copy{max-width:900px}footer{position:absolute;bottom:28px;left:76px;color:#${t.sub};font-size:12px;letter-spacing:.08em}@media print{@page{size:1280px 720px;margin:0}.slide{page-break-after:always}}
${animate?'@media screen{body{height:100vh;overflow:hidden;display:grid;place-items:center}.slide{display:none;box-shadow:0 30px 100px #000}.slide.active{display:block;animation:enter .65s cubic-bezier(.2,.8,.2,1)}.slide.active header{animation:up .55s .08s both}.slide.active figure,.slide.active .metrics,.slide.active .cards,.slide.active blockquote{animation:zoom .6s .2s both}.slide.active li{opacity:0;animation:left .45s both}.slide.active li:nth-child(1){animation-delay:.2s}.slide.active li:nth-child(2){animation-delay:.32s}.slide.active li:nth-child(3){animation-delay:.44s}.slide.active li:nth-child(4){animation-delay:.56s}.slide.active li:nth-child(5){animation-delay:.68s}@keyframes enter{from{opacity:0;transform:translateX(50px)}to{opacity:1;transform:none}}@keyframes up{from{opacity:0;transform:translateY(24px)}to{opacity:1;transform:none}}@keyframes left{from{opacity:0;transform:translateX(-24px)}to{opacity:1;transform:none}}@keyframes zoom{from{opacity:0;transform:scale(.92)}to{opacity:1;transform:none}}':''}</style></head><body><section class="slide cover"><div class="orb"></div><header><span>PRESENTATION</span><h2>${inline(title)}</h2><p>${inline(subtitle||'')}</p></header><main><div class="copy"><p>${inline(author||'')}</p></div></main></section>${pages}${animate?`<script>(()=>{const s=[...document.querySelectorAll('.slide')];let i=0;const show=n=>{i=Math.max(0,Math.min(s.length-1,n));s.forEach((x,k)=>x.classList.toggle('active',k===i))};addEventListener('keydown',e=>{if(['ArrowRight',' ','PageDown'].includes(e.key))show(i+1);if(['ArrowLeft','PageUp'].includes(e.key))show(i-1);if(e.key.toLowerCase()==='f')document.documentElement.requestFullscreen?.()});addEventListener('click',e=>show(i+(e.clientX>innerWidth*.35?1:-1)));show(0)})()</script>`:''}</body></html>`;
}
function addImageSafe(slide,image,box){ if(!image)return false;try{const o={...box};if(/^data:image\//.test(image))o.data=image;else o.path=image;slide.addImage(o);return true;}catch(_){return false;} }
function addTitle(pptx,slide,s,t,number){slide.addText(String(number).padStart(2,'0'),{x:.62,y:.38,w:.45,h:.25,fontSize:11,bold:true,color:t.accent,charSpacing:2});slide.addText(strip(s.title),{x:1.15,y:.3,w:11.3,h:.65,fontFace:'Aptos Display',fontSize:30,bold:true,color:t.title,breakLine:false,margin:0});if(s.subtitle)slide.addText(strip(s.subtitle),{x:1.16,y:.98,w:10.8,h:.35,fontSize:14,color:t.sub,margin:0});}
function addFooter(slide,title,t,i,n){slide.addText(strip(title),{x:.65,y:7.08,w:8,h:.2,fontSize:8,color:t.sub,margin:0});slide.addText(`${i+1} / ${n}`,{x:11.8,y:7.04,w:.85,h:.24,fontSize:9,bold:true,color:t.accent,align:'right',margin:0});}
function addBullets(slide,bullets,box,t,size=19){const runs=bullets.slice(0,6).map(b=>({text:strip(b),options:{bullet:{indent:18},hanging:4,color:t.body,fontSize:size,paraSpaceAfterPt:12,breakLine:true}}));if(runs.length)slide.addText(runs,{...box,fontFace:'Aptos',valign:'mid',margin:4,breakLine:false});}
async function buildPptx({title,subtitle,author,slides,theme,colors,animate=true}){
  slides=normalizeSlides({slides});
  const t=pickTheme(theme,colors),p=new PptxGenJS();p.defineLayout({name:'WIDE',width:13.333,height:7.5});p.layout='WIDE';p.author=author||'AI Agent';p.title=title||'Presentation';p.subject='Designed and verified presentation';p.lang='en-US';p.theme={headFontFace:'Aptos Display',bodyFontFace:'Aptos',lang:'en-US'};
  let s=p.addSlide();s.background={color:t.bg};s.addShape(p.ShapeType.ellipse,{x:9.5,y:-2.2,w:6.2,h:6.2,fill:{color:t.accent,transparency:40},line:{transparency:100}});s.addShape(p.ShapeType.rect,{x:.75,y:1.05,w:.14,h:4.9,fill:{color:t.accent},line:{transparency:100}});s.addText(strip(title||'Presentation'),{x:1.25,y:2.05,w:10.7,h:1.55,fontFace:'Aptos Display',fontSize:46,bold:true,color:t.title,margin:0,breakLine:false});if(subtitle)s.addText(strip(subtitle),{x:1.28,y:3.75,w:9.8,h:.7,fontSize:21,color:t.sub,margin:0});if(author)s.addText(strip(author),{x:1.28,y:5.85,w:5,h:.3,fontSize:13,color:t.body,margin:0});
  slides.forEach((d,i)=>{const slide=p.addSlide();slide.background={color:t.bg};slide.addShape(p.ShapeType.ellipse,{x:10.8,y:-1,w:3.6,h:3.6,fill:{color:t.accent2,transparency:78},line:{transparency:100}});addTitle(p,slide,d,t,i+1);const L=layoutFor(d,i);const bullets=d.bullets||[];
    if(L==='section'||L==='statement'){slide.addText(strip(d.content||bullets[0]||d.subtitle||''),{x:1.15,y:2.2,w:10.5,h:2.4,fontSize:32,bold:true,color:t.title,margin:0,valign:'mid'});slide.addShape(p.ShapeType.rect,{x:1.15,y:5.15,w:2.2,h:.12,fill:{color:t.accent},line:{transparency:100}});}
    else if(L==='quote'){slide.addText(`“${strip(d.quote)}”`,{x:1.05,y:1.75,w:11.2,h:3.6,fontSize:34,bold:true,color:t.title,margin:0,valign:'mid'});slide.addText(strip(d.attribution),{x:1.08,y:5.55,w:8,h:.4,fontSize:15,bold:true,color:t.accent,margin:0});}
    else if(L==='metrics'){d.metrics.slice(0,4).forEach((m,k)=>{const w=2.75,x=.75+k*3.08;slide.addShape(p.ShapeType.roundRect,{x,y:2.05,w,h:3.3,rectRadius:.08,fill:{color:t.surface,transparency:2},line:{color:t.accent,transparency:65,width:1}});slide.addText(strip(m.value),{x:x+.2,y:2.45,w:w-.4,h:.9,fontSize:32,bold:true,color:t.accent,align:'center',margin:0});slide.addText(strip(m.label),{x:x+.2,y:3.55,w:w-.4,h:1.1,fontSize:15,color:t.body,align:'center',valign:'mid',margin:2});});}
    else if(L==='cards'||L==='cards-auto'){const cards=d.cards.length?d.cards:bullets.map((b,k)=>({title:`0${k+1}`,text:b}));cards.slice(0,4).forEach((c,k)=>{const cols=cards.length>3?2:Math.min(3,cards.length),w=cols===2?5.55:3.55,x=.82+(k%cols)*(w+.32),y=1.7+Math.floor(k/cols)*2.25;slide.addShape(p.ShapeType.roundRect,{x,y,w,h:1.92,rectRadius:.06,fill:{color:t.surface},line:{color:k%2?t.accent2:t.accent,transparency:45}});slide.addText(strip(c.title||`0${k+1}`),{x:x+.2,y:y+.18,w:w-.4,h:.35,fontSize:14,bold:true,color:k%2?t.accent2:t.accent,margin:0});slide.addText(strip(c.text||c.content||''),{x:x+.2,y:y+.65,w:w-.4,h:1.05,fontSize:15,color:t.body,margin:0,valign:'mid'});});}
    else if(L==='chart'&&d.chart){const values=(d.chart.values||[]).map(Number),labels=d.chart.labels||values.map((_,k)=>String(k+1)),max=Math.max(1,...values);values.slice(0,7).forEach((v,k)=>{const x=1.15+k*1.55,h=3.4*(v/max);slide.addShape(p.ShapeType.roundRect,{x,y:5.75-h,w:.82,h,rectRadius:.04,fill:{color:k%2?t.accent2:t.accent},line:{transparency:100}});slide.addText(String(v),{x:x-.05,y:5.42-h,w:.92,h:.25,fontSize:10,bold:true,color:t.title,align:'center',margin:0});slide.addText(strip(labels[k]),{x:x-.28,y:5.92,w:1.4,h:.45,fontSize:10,color:t.sub,align:'center',margin:0});});}
    else if(d.image){const right=L!=='image-left';const imageBox={x:right?7.25:.72,y:1.55,w:5.35,h:4.95};slide.addShape(p.ShapeType.roundRect,{...imageBox,fill:{color:t.surface},line:{color:t.accent,transparency:55,width:1},rectRadius:.08,shadow:{type:'outer',color:'000000',opacity:.25,blur:2,angle:45,distance:2}});addImageSafe(slide,d.image,{x:imageBox.x+.06,y:imageBox.y+.06,w:imageBox.w-.12,h:imageBox.h-.12});addBullets(slide,bullets,{x:right?.78:6.45,y:1.58,w:5.85,h:4.85},t,18);if(!bullets.length&&d.content)slide.addText(strip(d.content),{x:right?.85:6.55,y:1.8,w:5.65,h:4.4,fontSize:19,color:t.body,valign:'mid',margin:4});}
    else {addBullets(slide,bullets,{x:1.05,y:1.55,w:11.1,h:4.95},t,20);if(!bullets.length&&d.content)slide.addText(strip(d.content),{x:1.05,y:1.7,w:11.1,h:4.6,fontSize:23,color:t.body,valign:'mid',margin:4});}
    if(d.notes)try{slide.addNotes(strip(d.notes));}catch(_){} addFooter(slide,title,t,i,slides.length);
  });
  let buf=await p.write('nodebuffer'); if(animate)buf=injectTransitions(buf,slides); return buf;
}
function injectTransitions(buffer,slides){const z=new AdmZip(buffer),entries=z.getEntries().filter(e=>/^ppt\/slides\/slide\d+\.xml$/.test(e.entryName));entries.forEach((e,i)=>{let x=e.getData().toString('utf8');if(/<p:transition\b/.test(x))return;const type=String((slides[i-1]&&slides[i-1].transition)||(['fade','push','wipe'][i%3])).toLowerCase();const child=type==='push'?'<p:push dir="l"/>':type==='wipe'?'<p:wipe dir="l"/>':'<p:fade/>';const tag=`<p:transition spd="med" advClick="1">${child}</p:transition>`;x=x.replace(/(<p:clrMapOvr[\s\S]*?<\/p:clrMapOvr>)/,`$1${tag}`);if(!x.includes(tag))x=x.replace(/<\/p:sld>/,`${tag}</p:sld>`);z.updateFile(e.entryName,Buffer.from(x));});return z.toBuffer();}
function validatePptx(buffer,{minSlides=2,requireVisuals=true,requireTransitions=true}={}){const z=new AdmZip(buffer),names=z.getEntries().map(e=>e.entryName),slideNames=names.filter(n=>/^ppt\/slides\/slide\d+\.xml$/.test(n)).sort((a,b)=>(+a.match(/\d+/)[0])-(+b.match(/\d+/)[0]));const issues=[],colors=new Set(),texts=[],transitions=[];for(const n of slideNames){const x=z.readAsText(n);for(const m of x.matchAll(/<a:srgbClr[^>]*val="([0-9A-Fa-f]{6})"/g))colors.add(m[1].toUpperCase());for(const m of x.matchAll(/<a:t>([\s\S]*?)<\/a:t>/g))texts.push(m[1].replace(/&amp;/g,'&'));if(/<p:transition\b/.test(x))transitions.push(n);}const media=names.filter(n=>/^ppt\/media\//.test(n));const notes=names.filter(n=>/^ppt\/notesSlides\/notesSlide\d+\.xml$/.test(n));if(slideNames.length<minSlides)issues.push(`only ${slideNames.length} slides`);if(texts.join(' ').trim().length<80)issues.push('insufficient presentation content');if(colors.size<3)issues.push('fewer than three design colors');if(requireVisuals&&!media.length&&!slideNames.some(n=>/<p:sp\b/.test(z.readAsText(n))))issues.push('no visual elements');if(requireTransitions&&transitions.length!==slideNames.length)issues.push(`transitions on ${transitions.length}/${slideNames.length} slides`);return{ok:!issues.length,issues,slides:slideNames.length,colors:[...colors],media:media.length,notes:notes.length,transitions:transitions.length,textCharacters:texts.join('').length};}
module.exports={THEMES,pickTheme,normalizeSlides,buildHtmlDeck,buildPptx,injectTransitions,validatePptx,layoutFor};
